name: GNU/Linux User Group
description: (Unofficial) GNU/Linux club focused on all things Unix and open-source!
author: Michael Riegert (nobodywasishere)
url: 
baseurl: 

source_code: https://github.com/nobodywasishere/tgslug

exclude: []
